Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.naive_bayes import GaussianNB, CategoricalNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Pisahkan fitur numerik dan kategorikal secara eksplisit
X_num = X_c_encoded.drop(columns=['Gender'])
X_cat = X_c_encoded[['Gender']]  # pastikan ini hanya kategorikal

# Split data
X_num_train, X_num_test, y_train, y_test = train_test_split(X_num, y, test_size=0.2, random_state=42)
X_cat_train, X_cat_test = train_test_split(X_cat, test_size=0.2, random_state=42)

# Pastikan target adalah array 1D
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

# Tangani NaN di data numerik sebelum scaling
X_num_train = X_num_train.fillna(X_num_train.median())
X_num_test = X_num_test.fillna(X_num_train.median())

# Scaling numerik
scaler = StandardScaler()
X_num_train = scaler.fit_transform(X_num_train)
X_num_test = scaler.transform(X_num_test)

# Model GaussianNB
gnb = GaussianNB()
gnb.fit(X_num_train, y_train)

# Model CategoricalNB
cnb = CategoricalNB()
cnb.fit(X_cat_train, y_train)

# Log-probabilitas
log_prob_gnb = gnb.predict_log_proba(X_num_test)
log_prob_cnb = cnb.predict_log_proba(X_cat_test)

# Gabungan prediksi log-proba
combined_log_prob = log_prob_gnb + log_prob_cnb
y_pred = gnb.classes_[np.argmax(combined_log_prob, axis=1)]

# Evaluasi
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipython-input-12-2558487726.py[0m in [0;36m<cell line: 0>[0;34m()[0m
[1;32m     14[0m [0;34m[0m[0m
[1;32m     15[0m [0;31m# Pastikan target adalah array 1D[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 16[0;31m [0my_train[0m [0;34m=[0m [0my_train[0m[0;34m.[0m[0mvalues[0m[0;34m.[0m[0mravel[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m [0my_test[0m [0;34m=[0m [0my_test[0m[0;34m.[0m[0mvalues[0m[0;34m.[0m[0mravel[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'values'

